from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 727)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.depCity = QtWidgets.QComboBox(self.centralwidget)
        self.depCity.setGeometry(QtCore.QRect(170, 30, 111, 21))
        self.depCity.setObjectName("depCity")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.depCity.addItem("")
        self.arrCity = QtWidgets.QComboBox(self.centralwidget)
        self.arrCity.setGeometry(QtCore.QRect(300, 30, 111, 21))
        self.arrCity.setObjectName("arrCity")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.arrCity.addItem("")
        self.depHour = QtWidgets.QComboBox(self.centralwidget)
        self.depHour.setGeometry(QtCore.QRect(300, 60, 111, 21))
        self.depHour.setObjectName("depHour")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.depHour.addItem("")
        self.searchSeat = QtWidgets.QPushButton(self.centralwidget)
        self.searchSeat.setGeometry(QtCore.QRect(440, 30, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.searchSeat.setFont(font)
        self.searchSeat.setObjectName("searchSeat")
        self.depDate = QtWidgets.QDateEdit(self.centralwidget)
        self.depDate.setGeometry(QtCore.QRect(170, 60, 110, 22))
        self.depDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 7, 19), QtCore.QTime(0, 0, 0)))
        self.depDate.setTime(QtCore.QTime(0, 0, 0))
        self.depDate.setCalendarPopup(True)
        self.depDate.setObjectName("depDate")
        self.resTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resTable.setGeometry(QtCore.QRect(90, 96, 431, 531))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resTable.setFont(font)
        self.resTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resTable.setRowCount(10)
        self.resTable.setColumnCount(4)
        self.resTable.setObjectName("resTable")
        item = QtWidgets.QTableWidgetItem()
        self.resTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resTable.setHorizontalHeaderItem(3, item)
        self.resTable.horizontalHeader().setCascadingSectionResizes(False)
        self.resTable.horizontalHeader().setDefaultSectionSize(100)
        self.resTable.horizontalHeader().setMinimumSectionSize(23)
        self.resTable.verticalHeader().setDefaultSectionSize(50)
        self.tryReservation = QtWidgets.QPushButton(self.centralwidget)
        self.tryReservation.setGeometry(QtCore.QRect(90, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tryReservation.setFont(font)
        self.tryReservation.setObjectName("tryReservation")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 100, 461, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("map.png"))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 110, 61, 531))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.checkBoxes = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.checkBoxes.setContentsMargins(0, 0, 0, 0)
        self.checkBoxes.setObjectName("checkBoxes")
        self.checkBox_01 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_01.setFont(font)
        self.checkBox_01.setObjectName("checkBox_01")
        self.checkBoxes.addWidget(self.checkBox_01)
        self.checkBox_02 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_02.setFont(font)
        self.checkBox_02.setObjectName("checkBox_02")
        self.checkBoxes.addWidget(self.checkBox_02)
        self.checkBox_03 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_03.setFont(font)
        self.checkBox_03.setObjectName("checkBox_03")
        self.checkBoxes.addWidget(self.checkBox_03)
        self.checkBox_04 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_04.setFont(font)
        self.checkBox_04.setObjectName("checkBox_04")
        self.checkBoxes.addWidget(self.checkBox_04)
        self.checkBox_05 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_05.setFont(font)
        self.checkBox_05.setObjectName("checkBox_05")
        self.checkBoxes.addWidget(self.checkBox_05)
        self.checkBox_06 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_06.setFont(font)
        self.checkBox_06.setObjectName("checkBox_06")
        self.checkBoxes.addWidget(self.checkBox_06)
        self.checkBox_07 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_07.setFont(font)
        self.checkBox_07.setObjectName("checkBox_07")
        self.checkBoxes.addWidget(self.checkBox_07)
        self.checkBox_08 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_08.setFont(font)
        self.checkBox_08.setObjectName("checkBox_08")
        self.checkBoxes.addWidget(self.checkBox_08)
        self.checkBox_09 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_09.setFont(font)
        self.checkBox_09.setObjectName("checkBox_09")
        self.checkBoxes.addWidget(self.checkBox_09)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBoxes.addWidget(self.checkBox_10)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 5, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 5, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.route_map = QtWidgets.QComboBox(self.centralwidget)
        self.route_map.setGeometry(QtCore.QRect(680, 50, 231, 22))
        self.route_map.setObjectName("route_map")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.route_map.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(720, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 30, 78, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_str = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_str.setFont(font)
        self.check_str.setObjectName("check_str")
        self.verticalLayout.addWidget(self.check_str)
        self.check_ktx = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_ktx.setFont(font)
        self.check_ktx.setObjectName("check_ktx")
        self.verticalLayout.addWidget(self.check_ktx)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.route_map.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.depCity.setCurrentText(_translate("MainWindow", "수서"))
        self.depCity.setItemText(0, _translate("MainWindow", "수서"))
        self.depCity.setItemText(1, _translate("MainWindow", "동탄"))
        self.depCity.setItemText(2, _translate("MainWindow", "지제"))
        self.depCity.setItemText(3, _translate("MainWindow", "천안아산"))
        self.depCity.setItemText(4, _translate("MainWindow", "오송"))
        self.depCity.setItemText(5, _translate("MainWindow", "공주"))
        self.depCity.setItemText(6, _translate("MainWindow", "익산"))
        self.depCity.setItemText(7, _translate("MainWindow", "정읍"))
        self.depCity.setItemText(8, _translate("MainWindow", "광주송정"))
        self.depCity.setItemText(9, _translate("MainWindow", "나주"))
        self.depCity.setItemText(10, _translate("MainWindow", "목포"))
        self.depCity.setItemText(11, _translate("MainWindow", "대전"))
        self.depCity.setItemText(12, _translate("MainWindow", "김천구미"))
        self.depCity.setItemText(13, _translate("MainWindow", "동대구"))
        self.depCity.setItemText(14, _translate("MainWindow", "신경주"))
        self.depCity.setItemText(15, _translate("MainWindow", "울산(통도사)"))
        self.depCity.setItemText(16, _translate("MainWindow", "부산"))
        self.arrCity.setItemText(0, _translate("MainWindow", "수서"))
        self.arrCity.setItemText(1, _translate("MainWindow", "동탄"))
        self.arrCity.setItemText(2, _translate("MainWindow", "지제"))
        self.arrCity.setItemText(3, _translate("MainWindow", "천안아산"))
        self.arrCity.setItemText(4, _translate("MainWindow", "오송"))
        self.arrCity.setItemText(5, _translate("MainWindow", "공주"))
        self.arrCity.setItemText(6, _translate("MainWindow", "익산"))
        self.arrCity.setItemText(7, _translate("MainWindow", "정읍"))
        self.arrCity.setItemText(8, _translate("MainWindow", "광주송정"))
        self.arrCity.setItemText(9, _translate("MainWindow", "나주"))
        self.arrCity.setItemText(10, _translate("MainWindow", "목포"))
        self.arrCity.setItemText(11, _translate("MainWindow", "대전"))
        self.arrCity.setItemText(12, _translate("MainWindow", "김천구미"))
        self.arrCity.setItemText(13, _translate("MainWindow", "동대구"))
        self.arrCity.setItemText(14, _translate("MainWindow", "신경주"))
        self.arrCity.setItemText(15, _translate("MainWindow", "울산(통도사)"))
        self.arrCity.setItemText(16, _translate("MainWindow", "부산"))
        self.depHour.setItemText(0, _translate("MainWindow", "00"))
        self.depHour.setItemText(1, _translate("MainWindow", "02"))
        self.depHour.setItemText(2, _translate("MainWindow", "04"))
        self.depHour.setItemText(3, _translate("MainWindow", "06"))
        self.depHour.setItemText(4, _translate("MainWindow", "08"))
        self.depHour.setItemText(5, _translate("MainWindow", "10"))
        self.depHour.setItemText(6, _translate("MainWindow", "12"))
        self.depHour.setItemText(7, _translate("MainWindow", "14"))
        self.depHour.setItemText(8, _translate("MainWindow", "16"))
        self.depHour.setItemText(9, _translate("MainWindow", "18"))
        self.depHour.setItemText(10, _translate("MainWindow", "20"))
        self.depHour.setItemText(11, _translate("MainWindow", "22"))
        self.searchSeat.setText(_translate("MainWindow", "검색"))
        self.depDate.setDisplayFormat(_translate("MainWindow", "yyyy.MM.dd"))
        item = self.resTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "기차"))
        item = self.resTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "출발/시간"))
        item = self.resTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "도착/시간"))
        item = self.resTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "좌석"))
        self.tryReservation.setText(_translate("MainWindow", "예약하기"))
        self.checkBox_01.setText(_translate("MainWindow", "예약"))
        self.checkBox_02.setText(_translate("MainWindow", "예약"))
        self.checkBox_03.setText(_translate("MainWindow", "예약"))
        self.checkBox_04.setText(_translate("MainWindow", "예약"))
        self.checkBox_05.setText(_translate("MainWindow", "예약"))
        self.checkBox_06.setText(_translate("MainWindow", "예약"))
        self.checkBox_07.setText(_translate("MainWindow", "예약"))
        self.checkBox_08.setText(_translate("MainWindow", "예약"))
        self.checkBox_09.setText(_translate("MainWindow", "예약"))
        self.checkBox_10.setText(_translate("MainWindow", "예약"))
        self.label_2.setText(_translate("MainWindow", "출발"))
        self.label_3.setText(_translate("MainWindow", "도착"))
        self.route_map.setItemText(0, _translate("MainWindow", "STR 노선도"))
        self.route_map.setItemText(1, _translate("MainWindow", "KTX 노선도 (경부선)"))
        self.route_map.setItemText(2, _translate("MainWindow", "KTX 노선도 (호남선)"))
        self.route_map.setItemText(3, _translate("MainWindow", "KTX 노선도 (경전선)"))
        self.route_map.setItemText(4, _translate("MainWindow", "KTX 노선도 (전라선)"))
        self.route_map.setItemText(5, _translate("MainWindow", "KTX 노선도 (강릉선)"))
        self.route_map.setItemText(6, _translate("MainWindow", "KTX 노선도 (중앙선)"))
        self.route_map.setItemText(7, _translate("MainWindow", "KTX 노선도 (중부내륙선)"))
        self.label_4.setText(_translate("MainWindow", "STR/KTX 노선도"))
        self.check_str.setText(_translate("MainWindow", "STR"))
        self.check_ktx.setText(_translate("MainWindow", "KTX"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

